version: "3.7"
      
services:
  db:
    container_name: db
    image: mysql:5.6
    volumes:
      - /home/data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: Asia/Seoul
    ports:
     - '3306:3306'
    networks:
      - global_network

  crawling:
    container_name: crawling
    build:
      context: ./crawling
    networks:
      - global_network

  rest-api:
    container_name: rest-api
    image: registry.ccontena.com/rest-api
    ports:
      - "8081:8081"
    networks:
      - global_network

networks:
  global_network:
    external:
      name: global_network