version: "3.7"

networks:
  default:
    external:
      name: global_network

services:
  db:
    image: mysql:5.6
    volumes:
      - ~/data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: Asia/Seoul
    ports:
     - '3306:3306'
    container_name: db

  crawling:
    build:
      context: ./crawling
    container_name: crawling

  rest-api:
    build:
      context: ./rest-api
    ports:
      - "8081:8081"
    container_name: rest-api
