version: "3.7"

services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - global_network

  registry:
    container_name: registry
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./registry/data:/var/lib/registry
    networks:
      - global_network

networks:
  global_network:
    external:
      name: global_network
