version: "3.7"

services:
  nginx:
    container_name: nginx
    image: "nginx:alpine"
    ports:
      - 443:443
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - global_network

networks:
  global_network:
    external:
      name: global_network
